import enum

class UserRole(str, enum.Enum):
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    HOSPITAL_ADMIN = "HOSPITAL_ADMIN"
    CAMPAIGN_MANAGER = "CAMPAIGN_MANAGER"
    CLINICAL_REVIEWER = "CLINICAL_REVIEWER"

class HospitalStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    READY_FOR_CAMPAIGNS = "READY_FOR_CAMPAIGNS"
    INACTIVE = "INACTIVE"

class CampaignStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    SCHEDULED = "SCHEDULED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"

class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    CALLING = "CALLING"
    CONNECTED = "CONNECTED"
    COMPLETED = "COMPLETED"
    NO_ANSWER = "NO_ANSWER"
    BUSY = "BUSY"
    VOICEMAIL = "VOICEMAIL"
    DROPPED = "DROPPED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    CALLBACK_SCHEDULED = "CALLBACK_SCHEDULED"
    ESCALATED = "ESCALATED"
    MANUAL_FOLLOW_UP = "MANUAL_FOLLOW_UP"
    FAILED = "FAILED"

class CallOutcome(str, enum.Enum):
    SUCCESSFUL_COMPLETION = "SUCCESSFUL_COMPLETION"
    NO_ANSWER = "NO_ANSWER"
    BUSY = "BUSY"
    VOICEMAIL = "VOICEMAIL"
    DROPPED = "DROPPED"
    INVALID_NUMBER = "INVALID_NUMBER"
    DECLINED = "DECLINED"
    CALLBACK_REQUESTED = "CALLBACK_REQUESTED"
    ESCALATION_TRIGGERED = "ESCALATION_TRIGGERED"
    TECHNICAL_FAILURE = "TECHNICAL_FAILURE"

class EscalationStatus(str, enum.Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_REVIEW = "IN_REVIEW"
    WAITING_FOR_INFORMATION = "WAITING_FOR_INFORMATION"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class UrgencyLevel(str, enum.Enum):
    ROUTINE = "ROUTINE"
    CONCERNING = "CONCERNING"
    URGENT = "URGENT"
    UNCERTAIN = "UNCERTAIN"

class RiskTier(str, enum.Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
